// Automatically generated by rust_swig
package com.rust.app.swapiclient.swapi;
import androidx.annotation.NonNull;

public interface SwapiPeopleLoadedListener {


    void onLoaded(@NonNull People [] s);


    void onError(@NonNull String s);

}
